
services:
  - type: web
    name: TruyenChuTT
    env: java
   buildCommand: "mvn clean install"
startCommand: "java -jar target/*.jar"

    envVars:
      - key: JAVA_VERSION
        value: 17
    plan: free
